{
	"version": 1572033293,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tou.png",
		"images/cas.png",
		"images/von.png",
		"images/bar.png",
		"images/ske.png",
		"images/com.png",
		"images/tiledbackground.png",
		"media/smiler.ogg",
		"media/cluedo.ogg",
		"media/musclor.ogg",
		"media/droids.ogg",
		"media/manor.ogg",
		"media/piratas.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"tournefolle.mp4"
	]
}